### PR TITLE
John/create course form

### PR DESCRIPTION
**Pull request by schiltz3**
### bootstrap_test.html
* Fixed `bootstrap_test.html` not having name tags which was confusing
### create.html
* Finished `create.html` and added comment block at top of file
  * Added the tag `required="true"` to inputs to prevent the form from being submitted with empty fields
### create.py
* Worked on `create.py`
  * Added user validation to inputs
  * Added complete input validation
  * Now correctly creates courses using the CourseUtil
### Project changes
* Set docstring format
  * To create docs for a method type `"""` then press enter
  * Next add the `@pre:`, `@post:`, and `@par:` tags. A list of all possible tags can be found [here](https://www.doxygen.nl/manual/commands.html)

### CODE REVIEW

**Comment by schiltz3** [comment]
[create course form html](https://trello.com/c/L8j22ML4/31-create-course-form-html)

**Comment by Quaddy09** [comment]
Looks good, all good to me

**Review by Quaddy09 — COMMENTED** [review]
Looks good

**Comment by schiltz3** [comment]
> Looks good
Automated formating had not gone though yet

**Comment by schiltz3** [comment]
[create course form html](https://trello.com/c/L8j22ML4/31-create-course-form-html)

**Comment by llisaeva** [comment]
Looks great!

**Review by llisaeva — APPROVED** [review]

**Review by TouKoua — APPROVED** [review]

**Pull request merged**
